import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/src/components/Footer";
import Script from "next/script";
import { ThemeProvider } from "@/components/theme-provider";
import HamburgerMenu from "@/components/hamburger-menu";
import { Snail, SnailIcon } from "lucide-react";
import Link from "next/link";
import Container from "@/components/container";
import Header from "@/components/header";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "relative min-h-screen bg-background font-sans antialiased",
          outfit.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div>
            {children}
            <div className="col-start-2 col-end-3">
              <Footer />
            </div>
          </div>
        </ThemeProvider>
        <Script
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2092024278385736"
          crossOrigin="anonymous"
          async
        ></Script>
      </body>
    </html>
  );
}
