import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Navigation from "@/src/components/Navigation";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} bg-zinc-900 relative`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
